# This Dockerfile was generated by SDuSDi for dlstreamer:devel
FROM intel/dlstreamer:devel

SHELL ["bash", "-c"]
USER root

# install vim, terminator, tmux and tmuxinator
RUN apt-get update && \
    apt-get install -y vim && \
    apt-get install -y tmux rubygems && \
    gem install thor -v 1.2.2 && \
    gem install tmuxinator -v 1.1.5

# upgrade python pip and install dependencies
RUN python3 -m pip install --upgrade pip && \
    python3 -m pip install openvino-dev[onnx] && \
    python3 -m pip install paho-mqtt

# install mosquitto
RUN apt install -y mosquitto mosquitto-clients

# download models
RUN /opt/intel/dlstreamer/samples/download_models.sh

# download test video
WORKDIR /home/dlstreamer/
COPY . .
# RUN wget https://github.com/intel-iot-devkit/sample-videos/raw/master/person-bicycle-car-detection.mp4

##########################
# EJECUCIÓN DEL PROGRAMA #
##########################

USER dlstreamer

# setup entrypoint
COPY ./entrypoint.sh /
COPY ./tmux /

ENTRYPOINT ["./entrypoint.sh"]
CMD ["bash"]
